import { generateHelp, generateCommandTable } from "./help"
import path from "path"

const root = path.resolve(import.meta.dir, "../../../..") + "/"

const TABLE_PATH = root + "packages/kilo-docs/markdoc/partials/cli-commands-table.md"
const REFERENCE_PATH = root + "packages/kilo-docs/pages/code-with-ai/platforms/cli-reference.md"

const table = await generateCommandTable()
await Bun.write(TABLE_PATH, `<!-- Auto-generated by script/generate-cli-docs.ts — do not edit manually -->\n\n${table}`)
console.log(`wrote ${TABLE_PATH}`)

const cwd = process.cwd()
const reference = (await generateHelp({ all: true, format: "md" })).replaceAll(cwd, ".")
await Bun.write(
  REFERENCE_PATH,
  `---
title: "CLI Command Reference"
description: "Complete reference for all Kilo CLI commands and subcommands"
---

# CLI Command Reference

<!-- Auto-generated by script/generate-cli-docs.ts — do not edit manually -->

${reference}`,
)
console.log(`wrote ${REFERENCE_PATH}`)
